/* ==========================================================================
   YOR Estate - Seed Data
   ========================================================================== */

const INITIAL_DATA = {
  // Financial Year datasets for Sales Performance
  fyData: {
    "2026-27": { totalValue: "₹96.4 Cr", totalSold: "184", monthSold: "23", monthValue: "₹12.8 Cr", rentals: "892" },
    "2025-26": { totalValue: "₹84.7 Cr", totalSold: "161", monthSold: "18", monthValue: "₹9.6 Cr", rentals: "814" },
    "2024-25": { totalValue: "₹72.2 Cr", totalSold: "139", monthSold: "16", monthValue: "₹8.1 Cr", rentals: "748" }
  },

  // Properties with Survey Numbers (unique identifier) and Multi-State Legal Verification data
  properties: [
    {
      id: "PROP-001",
      name: "Green Valley Plot",
      surveyNo: "123/2A",
      location: "Devenahalli, Bengaluru",
      state: "Karnataka",
      type: "Land",
      area: "5.2 Acres",
      outlet: "YOR South",
      legalStatus: "Approved",
      legalStage: "Final registration entry",
      assignedLegalOfficer: "Priya Nair (Senior Legal)",
      submittedBy: "Outlet Admin (YOR South)",
      submittedDate: "10 May 2026",
      valuation: "₹12.5 Cr",
      rawValuation: 125000000,
      valuationHistory: [10.2, 10.8, 11.4, 11.9, 12.5],
      images: 4,
      docsCount: 6,
      active: true,
      firstOwnerInfo: {
        originalOwner: "K. Narayana Gowda (Ancestral Allottee)",
        acquisitionYear: "1994",
        parentDeedNo: "DOC/BHOOMI/GR-419/1994",
        sroOffice: "Devanahalli Sub-Registrar Office",
        extentArea: "5.20 Acres (Demarcated Boundary)",
        surveyDemarcation: "Sy. No. 123/2A (Original agricultural conversion in 2004)",
        khataType: "Bhoomi RTC & A-Khata Extract",
        parentRemarks: "Original ancestral land grant followed by DC non-agricultural conversion order #ALN-88/2004 for residential township."
      },
      ownershipChain: [
        {
          step: 1,
          date: "12 Oct 2004",
          year: "2004",
          type: "Agricultural DC Conversion & Parent Grant",
          seller: "Government of Karnataka (Revenue Dept)",
          buyer: "K. Narayana Gowda & Family",
          price: "₹45.0 L",
          rawPrice: 4500000,
          regDocNo: "REG-KA-2004/8912",
          sro: "Devanahalli SRO",
          platform: "Pre-Platform / Government Grant",
          agent: "Government Revenue Demarcation",
          status: "Archived Parent Deed",
          notes: "Ancestral agricultural conversion order issued under Karnataka Land Revenue Act Section 95."
        },
        {
          step: 2,
          date: "18 Jun 2018",
          year: "2018",
          type: "First Sale via YOR Platform",
          seller: "K. Narayana Gowda",
          buyer: "Brigade Horizon Developers Ltd",
          price: "₹4.80 Cr",
          rawPrice: 48000000,
          regDocNo: "SRO/DEV/4412/2018",
          sro: "Devanahalli SRO (Book 1, Vol 841)",
          platform: "YOR Primary Acquisition",
          agent: "Sarah Lim (Apex Luxury Realtors)",
          status: "Registered & Verified",
          notes: "First acquisition through YOR Estate network. Kaveri 2.0 Nil-EC verified (1996-2018)."
        },
        {
          step: 3,
          date: "04 Feb 2022",
          year: "2022",
          type: "Resale #1 via YOR Estate",
          seller: "Brigade Horizon Developers Ltd",
          buyer: "Dr. Vikramaditya Reddy (Reddy Healthcare Holdings)",
          price: "₹8.20 Cr",
          rawPrice: 82000000,
          regDocNo: "SRO/DEV/1109/2022",
          sro: "Devanahalli SRO (Book 1, Vol 1092)",
          platform: "YOR Resale Hub",
          agent: "Ananya Sharma (Skyline Channel Partners)",
          status: "Registered & Verified",
          notes: "Resold through YOR platform. Mutation MR-44/2018 updated with Bhoomi RTC revenue rolls."
        },
        {
          step: 4,
          date: "20 May 2025",
          year: "2025",
          type: "Resale #2 via YOR Estate (Current Title)",
          seller: "Dr. Vikramaditya Reddy",
          buyer: "Aria Global Asset Fund / Tan Wei Ming (Present Owner)",
          price: "₹12.50 Cr",
          rawPrice: 125000000,
          regDocNo: "SRO/DEV/7841/2025",
          sro: "Devanahalli SRO (Book 1, Vol 1488)",
          platform: "YOR Private Client Resale",
          agent: "Sarah Lim (Apex Luxury Realtors)",
          status: "Active Current Title",
          notes: "Present ownership. Current valuation ₹12.5 Cr. 30-Year Nil Encumbrance Certificate verified on Kaveri 2.0. APF cleared by SBI & HDFC."
        }
      ],
      stages: {
        intake: { title: "Document upload & intake", assignedRole: "Outlet Admin", status: "done", completedBy: "Riyas Ali (Outlet Admin)", date: "10 May 2026" },
        survey: { title: "Survey number cross-check", assignedRole: "Outlet Admin", status: "done", completedBy: "Riyas Ali (Outlet Admin)", date: "11 May 2026" },
        encumbrance: { title: "Encumbrance verification", assignedRole: "Outlet Admin", status: "done", completedBy: "Priya Nair (Legal Team)", date: "12 May 2026" },
        ho_signoff: { title: "HO sign-off", assignedRole: "HO Admin", status: "done", completedBy: "Sarah Coleman (HO Admin)", date: "13 May 2026" },
        final_reg: { title: "Final registration entry", assignedRole: "HO Admin", status: "done", completedBy: "Sarah Coleman (HO Admin)", date: "14 May 2026" }
      },
      legalChecklist: {
        "ka_title": { status: "Verified", verifiedBy: "Priya Nair", date: "11 May 2026", remarks: "30-year clear marketable title chain verified" },
        "ka_ec": { status: "Verified", verifiedBy: "Priya Nair", date: "12 May 2026", remarks: "Kaveri 2.0 Nil-Encumbrance Certificate verified (1996-2026)" },
        "ka_rtc": { status: "Verified", verifiedBy: "Priya Nair", date: "11 May 2026", remarks: "Bhoomi RTC Khata extract matched with Survey 123/2A" },
        "ka_mutation": { status: "Verified", verifiedBy: "Priya Nair", date: "12 May 2026", remarks: "Mutation Register Extract MR-44/2018 in order" },
        "ka_zoning": { status: "Verified", verifiedBy: "Priya Nair", date: "12 May 2026", remarks: "BDA Master Plan 2031 yellow residential zone confirmed" },
        "ka_apf": { status: "Verified", verifiedBy: "Priya Nair", date: "13 May 2026", remarks: "SBI & HDFC APF Project Loan Sanction letters verified" },
        "ka_advocate": { status: "Verified", verifiedBy: "Priya Nair", date: "13 May 2026", remarks: "Clear legal opinion from Senior Advocate V. S. Rao" }
      }
    },
    {
      id: "PROP-002",
      name: "Riverside Waterfront Penthouse",
      surveyNo: "144/3B",
      location: "Marine Drive, Kochi",
      state: "Kerala",
      type: "Residential",
      area: "3,850 sq.ft",
      outlet: "YOR Central",
      legalStatus: "In-Review",
      legalStage: "Encumbrance verification",
      assignedLegalOfficer: "Adv. Rajesh Menon",
      submittedBy: "Outlet Admin (YOR Central)",
      submittedDate: "12 May 2026",
      valuation: "₹8.4 Cr",
      rawValuation: 84000000,
      valuationHistory: [7.2, 7.6, 7.9, 8.1, 8.4],
      images: 6,
      docsCount: 5,
      active: true,
      firstOwnerInfo: {
        originalOwner: "Capt. E. K. Varma (Retired Naval Commander)",
        acquisitionYear: "1998",
        parentDeedNo: "KL-EKM/DOC-1102/1998",
        sroOffice: "Ernakulam Sub-Registrar Office",
        extentArea: "3,850 sq.ft (Tower B, Penthouse Unit 1401)",
        surveyDemarcation: "Resurvey Block 24, Sy. No. 144/3B, Kanayannur Taluk",
        khataType: "Thandaper Account #4820 (Kochi Municipal Corporation)",
        parentRemarks: "Original land parcel owned by Varma family before joint-development with Puravankara Waterfront."
      },
      ownershipChain: [
        {
          step: 1,
          date: "14 Nov 1998",
          year: "1998",
          type: "Joint Development Allotment",
          seller: "Puravankara Marine Infrastructure",
          buyer: "Capt. E. K. Varma",
          price: "₹1.20 Cr",
          rawPrice: 12000000,
          regDocNo: "KL-EKM/4491/1998",
          sro: "Ernakulam SRO",
          platform: "Original Landowner Allotment",
          agent: "Direct Builder Allotment",
          status: "Archived Parent Deed",
          notes: "Original owner allocation in beachfront high-rise tower."
        },
        {
          step: 2,
          date: "08 Sep 2019",
          year: "2019",
          type: "First Sale via YOR Platform",
          seller: "Capt. E. K. Varma & Legal Heirs",
          buyer: "Mathews & George Gulf Investments",
          price: "₹4.50 Cr",
          rawPrice: 45000000,
          regDocNo: "SRO/EKM/7721/2019",
          sro: "Ernakulam SRO (Book 1, Vol 512)",
          platform: "YOR NRI Portal",
          agent: "James Tan (Prime Horizon Realty)",
          status: "Registered & Verified",
          notes: "Purchased as luxury beachfront holiday home. Full title verification done by Adv. Rajesh Menon."
        },
        {
          step: 3,
          date: "15 Jan 2024",
          year: "2024",
          type: "Resale via YOR Platform (Current Owner)",
          seller: "Mathews & George Gulf Investments",
          buyer: "Ahmed Al Faisal (NRI Luxury Portfolio)",
          price: "₹8.40 Cr",
          rawPrice: 84000000,
          regDocNo: "SRO/EKM/2104/2024",
          sro: "Ernakulam SRO (Book 1, Vol 980)",
          platform: "YOR Ultra-HNW Resale",
          agent: "Mohammed Farooq (Malabar Realty Group)",
          status: "Active Current Title",
          notes: "Present ownership. Thandaper Account #4820 transferred. High rental yield asset generating ₹55,200/mo."
        }
      ],
      stages: {
        intake: { title: "Document upload & intake", assignedRole: "Outlet Admin", status: "done", completedBy: "Riyas Ali (Outlet Admin)", date: "12 May 2026" },
        survey: { title: "Survey number cross-check", assignedRole: "Outlet Admin", status: "done", completedBy: "Riyas Ali (Outlet Admin)", date: "13 May 2026" },
        encumbrance: { title: "Encumbrance verification", assignedRole: "Outlet Admin", status: "review", completedBy: "Adv. Rajesh Menon (Legal Team)", date: "In Progress" },
        ho_signoff: { title: "HO sign-off", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" },
        final_reg: { title: "Final registration entry", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" }
      },
      legalChecklist: {
        "kl_title": { status: "Verified", verifiedBy: "Adv. Rajesh Menon", date: "13 May 2026", remarks: "20-year title flow verified via Ernakulam Sub-Registrar" },
        "kl_thandaper": { status: "Verified", verifiedBy: "Adv. Rajesh Menon", date: "13 May 2026", remarks: "Thandaper Account #4820 with Kanayannur Taluk verified" },
        "kl_ec": { status: "Under review", verifiedBy: null, date: "14 May 2026", remarks: "Awaiting e-Treasury certified EC from 1996 to 2026" },
        "kl_sketch": { status: "Verified", verifiedBy: "Adv. Rajesh Menon", date: "13 May 2026", remarks: "Village Officer location sketch & possession cert verified" },
        "kl_wetland": { status: "Verified", verifiedBy: "Adv. Rajesh Menon", date: "14 May 2026", remarks: "Excluded from Kerala Conservation of Paddy Land & Wetland Act Data Bank" },
        "kl_rera": { status: "Under review", verifiedBy: null, date: "14 May 2026", remarks: "K-RERA Certificate verification under process" }
      }
    },
    {
      id: "PROP-003",
      name: "Cyber Pearl Commercial Tech Park",
      surveyNo: "456/38",
      location: "HITEC City, Hyderabad",
      state: "Telangana",
      type: "Commercial",
      area: "12 Acres",
      outlet: "YOR Central",
      legalStatus: "Resubmit",
      legalStage: "Survey number cross-check",
      assignedLegalOfficer: "Adv. Suresh Varma",
      submittedBy: "Outlet Admin (YOR Central)",
      submittedDate: "08 May 2026",
      valuation: "₹25.0 Cr",
      rawValuation: 250000000,
      valuationHistory: [20.0, 21.5, 23.0, 24.2, 25.0],
      images: 2,
      docsCount: 4,
      active: true,
      firstOwnerInfo: {
        originalOwner: "T. Rajagopal Rao & Brothers",
        acquisitionYear: "2001",
        parentDeedNo: "TG-HYD/DOC-8891/2001",
        sroOffice: "Serilingampally Sub-Registrar Office",
        extentArea: "12.00 Acres (IT/ITES Special Commercial Zone)",
        surveyDemarcation: "Sy. No. 456/38 (Dharani Passbook T080901290)",
        khataType: "GHMC Commercial Property Tax Assessment #91024",
        parentRemarks: "Originally pattadar agricultural land demarcated and converted by APIIC / TSIIC for Cyberabad IT corridor."
      },
      ownershipChain: [
        {
          step: 1,
          date: "10 Mar 2001",
          year: "2001",
          type: "Pattadar Title Demarcation",
          seller: "Government of Andhra Pradesh / TSIIC",
          buyer: "T. Rajagopal Rao",
          price: "₹85.0 L",
          rawPrice: 8500000,
          regDocNo: "TG-SER/3012/2001",
          sro: "Serilingampally SRO",
          platform: "Pre-Platform APIIC Allocation",
          agent: "TSIIC Allotment Cell",
          status: "Archived Parent Deed",
          notes: "Commercial zoning clearance under Cyberabad Master Plan."
        },
        {
          step: 2,
          date: "22 Nov 2017",
          year: "2017",
          type: "First Sale via YOR Platform",
          seller: "T. Rajagopal Rao & Family",
          buyer: "Deccan Commercial Assets REIT",
          price: "₹14.50 Cr",
          rawPrice: 145000000,
          regDocNo: "SRO/SER/9912/2017",
          sro: "Serilingampally SRO (Book 1, Vol 1204)",
          platform: "YOR Institutional Desk",
          agent: "Vikramaditya Roy (Deccan Prestige Estates)",
          status: "Registered & Verified",
          notes: "Commercial office park development with Grade-A LEED Gold certification."
        },
        {
          step: 3,
          date: "11 Aug 2023",
          year: "2023",
          type: "Resale via YOR Platform (Current Owner)",
          seller: "Deccan Commercial Assets REIT",
          buyer: "Cyber Pearl Holdings Pte Ltd",
          price: "₹25.00 Cr",
          rawPrice: 250000000,
          regDocNo: "SRO/SER/4410/2023",
          sro: "Serilingampally SRO (Book 1, Vol 1890)",
          platform: "YOR Commercial Syndicate",
          agent: "Vikramaditya Roy (Deccan Prestige Estates)",
          status: "Active Current Title",
          notes: "Current institutional ownership. Boundary survey 456/38 undergoing revenue re-demarcation sketch."
        }
      ],
      stages: {
        intake: { title: "Document upload & intake", assignedRole: "Outlet Admin", status: "done", completedBy: "Riyas Ali (Outlet Admin)", date: "08 May 2026" },
        survey: { title: "Survey number cross-check", assignedRole: "Outlet Admin", status: "review", completedBy: "Adv. Suresh Varma", date: "Action Needed" },
        encumbrance: { title: "Encumbrance verification", assignedRole: "Outlet Admin", status: "pending", completedBy: null, date: "Pending" },
        ho_signoff: { title: "HO sign-off", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" },
        final_reg: { title: "Final registration entry", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" }
      },
      legalChecklist: {
        "tg_dharani": { status: "Resubmit", verifiedBy: "Adv. Suresh Varma", date: "09 May 2026", remarks: "Survey number 456/38 boundary mismatch with Dharani Passbook. Requires revenue demarcation sketch." },
        "tg_title": { status: "Verified", verifiedBy: "Adv. Suresh Varma", date: "09 May 2026", remarks: "30-year registered title chain verified" },
        "tg_ec": { status: "Verified", verifiedBy: "Adv. Suresh Varma", date: "10 May 2026", remarks: "Online EC from IGRS Telangana verified Nil" },
        "tg_hmda": { status: "Under review", verifiedBy: null, date: "10 May 2026", remarks: "HMDA multi-storey building layout sanction under review" },
        "tg_apf": { status: "Verified", verifiedBy: "Adv. Suresh Varma", date: "11 May 2026", remarks: "Axis & HDFC Commercial APF Pre-Sanction verified" }
      }
    },
    {
      id: "PROP-004",
      name: "Marina Sea Breeze Residences",
      surveyNo: "90/4",
      location: "OMR, Chennai",
      state: "Tamil Nadu",
      type: "Residential",
      area: "2,800 sq.ft",
      outlet: "YOR South",
      legalStatus: "Pending",
      legalStage: "Document upload & intake",
      assignedLegalOfficer: "Priya Nair (Senior Legal)",
      submittedBy: "Outlet Admin (YOR South)",
      submittedDate: "15 May 2026",
      valuation: "₹18.6 Cr",
      rawValuation: 186000000,
      valuationHistory: [15.0, 16.2, 17.0, 17.8, 18.6],
      images: 8,
      docsCount: 3,
      active: true,
      firstOwnerInfo: {
        originalOwner: "S. Muruganatham & S. Ramanathan",
        acquisitionYear: "1996",
        parentDeedNo: "TN-CH/DOC-3401/1996",
        sroOffice: "Adyar Sub-Registrar Office",
        extentArea: "2,800 sq.ft (East Coast Highway Corridor)",
        surveyDemarcation: "Old Sy. 90/4, New T.S. No. 12/B, Block 8, Sholinganallur",
        khataType: "Patta / Chitta Extract #7821 (e-Services Tamil Nadu)",
        parentRemarks: "Original ancestral coastal estate partitioned under family settlement deed #1104/1996."
      },
      ownershipChain: [
        {
          step: 1,
          date: "15 May 1996",
          year: "1996",
          type: "Family Partition Deed & Parent Title",
          seller: "Muruganatham Ancestral Estate",
          buyer: "S. Ramanathan",
          price: "₹28.0 L",
          rawPrice: 2800000,
          regDocNo: "TN-ADYAR/1104/1996",
          sro: "Adyar SRO",
          platform: "Ancestral Family Settlement",
          agent: "Self-Registered",
          status: "Archived Parent Deed",
          notes: "Registered family partition deed with clear boundaries."
        },
        {
          step: 2,
          date: "14 Jul 2020",
          year: "2020",
          type: "First Sale via YOR Platform",
          seller: "S. Ramanathan",
          buyer: "Coromandel Sea View Villas LLP",
          price: "₹9.80 Cr",
          rawPrice: 98000000,
          regDocNo: "SRO/ADYAR/5512/2020",
          sro: "Adyar SRO (Book 1, Vol 774)",
          platform: "YOR Luxury Coastal Desk",
          agent: "Kavitha Krishnan (Coromandel Property Advisory)",
          status: "Registered & Verified",
          notes: "Converted to premium coastal residential development with CMDA planning approval."
        },
        {
          step: 3,
          date: "12 Mar 2025",
          year: "2025",
          type: "Resale via YOR Platform (Current Owner)",
          seller: "Coromandel Sea View Villas LLP",
          buyer: "Vance Global Estates / Siyad Sirajudeen",
          price: "₹18.60 Cr",
          rawPrice: 186000000,
          regDocNo: "SRO/ADYAR/8819/2025",
          sro: "Adyar SRO (Book 1, Vol 1120)",
          platform: "YOR Premier Private Client",
          agent: "Sarah Lim (Apex Luxury Realtors)",
          status: "Active Current Title",
          notes: "Current registered ownership. Patta extract verified. 30-year Tnreginet EC clean."
        }
      ],
      stages: {
        intake: { title: "Document upload & intake", assignedRole: "Outlet Admin", status: "done", completedBy: "Riyas Ali (Outlet Admin)", date: "15 May 2026" },
        survey: { title: "Survey number cross-check", assignedRole: "Outlet Admin", status: "pending", completedBy: null, date: "Pending" },
        encumbrance: { title: "Encumbrance verification", assignedRole: "Outlet Admin", status: "pending", completedBy: null, date: "Pending" },
        ho_signoff: { title: "HO sign-off", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" },
        final_reg: { title: "Final registration entry", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" }
      },
      legalChecklist: {
        "tn_title": { status: "Under review", verifiedBy: null, date: "15 May 2026", remarks: "Uploaded 30-year prior title deed chain awaiting legal scrutiny" },
        "tn_patta": { status: "Under review", verifiedBy: null, date: "15 May 2026", remarks: "e-Services Patta/Chitta Extract in seller's name uploaded" },
        "tn_ec": { status: "Under review", verifiedBy: null, date: "15 May 2026", remarks: "Tnreginet 30-year EC uploaded" },
        "tn_dtcp": { status: "Under review", verifiedBy: null, date: "15 May 2026", remarks: "CMDA Planning Permit uploaded" },
        "tn_apf": { status: "Pending", verifiedBy: null, date: "15 May 2026", remarks: "Bank APF clearance pending" }
      }
    },
    {
      id: "PROP-005",
      name: "The Lennox Luxury Penthouse",
      surveyNo: "221/11A",
      location: "Worli, Mumbai",
      state: "Maharashtra",
      type: "Residential",
      area: "4,200 sq.ft",
      outlet: "YOR West",
      legalStatus: "Approved",
      legalStage: "Final registration entry",
      assignedLegalOfficer: "Adv. Amit Kulkarni",
      submittedBy: "Outlet Admin (YOR West)",
      submittedDate: "02 May 2026",
      valuation: "₹32.0 Cr",
      rawValuation: 320000000,
      valuationHistory: [26.0, 28.0, 29.5, 30.8, 32.0],
      images: 5,
      docsCount: 6,
      active: true,
      firstOwnerInfo: {
        originalOwner: "K. R. Wadia & Sons (Industrialist Family)",
        acquisitionYear: "1988",
        parentDeedNo: "MH-MUM/DOC-0982/1988",
        sroOffice: "Mumbai City Old Custom House SRO",
        extentArea: "4,200 sq.ft (Tower Lennox, Sky Villa 2801)",
        surveyDemarcation: "CS No. 221/11A, Lower Parel / Worli Sea Face Division",
        khataType: "Mahabhulekh 7/12 & Property Card #4410",
        parentRemarks: "Original mill land redevelopment sanctioned under DCR 58 with BMC."
      },
      ownershipChain: [
        {
          step: 1,
          date: "10 Dec 1988",
          year: "1988",
          type: "Perpetual Conveyance Deed",
          seller: "Bombay Port & Land Trust",
          buyer: "K. R. Wadia & Sons",
          price: "₹65.0 L",
          rawPrice: 6500000,
          regDocNo: "MH-MUM/1192/1988",
          sro: "Mumbai SRO",
          platform: "Pre-Platform Historical Parcel",
          agent: "Direct Conveyance",
          status: "Archived Parent Deed",
          notes: "Parent registered title deed with clean marketable title flow."
        },
        {
          step: 2,
          date: "16 Apr 2016",
          year: "2016",
          type: "First Sale via YOR Platform",
          seller: "Wadia Realty Trust",
          buyer: "Harish Singhania (Singhania Textiles)",
          price: "₹18.50 Cr",
          rawPrice: 185000000,
          regDocNo: "SRO/WORLI/3340/2016",
          sro: "Worli SRO (Book 1, Vol 990)",
          platform: "YOR Ultra-Luxury Advisory",
          agent: "Sarah Lim (Apex Luxury Realtors)",
          status: "Registered & Verified",
          notes: "Acquired as bespoke penthouse suite. Full MahaRERA verification completed."
        },
        {
          step: 3,
          date: "28 Feb 2024",
          year: "2024",
          type: "Resale via YOR Platform (Current Owner)",
          seller: "Harish Singhania",
          buyer: "Apex Global Sovereign Holdings",
          price: "₹32.00 Cr",
          rawPrice: 320000000,
          regDocNo: "SRO/WORLI/7719/2024",
          sro: "Worli SRO (Book 1, Vol 1450)",
          platform: "YOR Private Banking Resale",
          agent: "Rahul Kapoor (Matrix Commercial Partners)",
          status: "Active Current Title",
          notes: "Current registered ownership. Full occupation certificate (OC) and BMC property card in order. Sub-Registrar 30-year search report confirmed Nil Encumbrance."
        }
      ],
      stages: {
        intake: { title: "Document upload & intake", assignedRole: "Outlet Admin", status: "done", completedBy: "Outlet Admin (YOR West)", date: "02 May 2026" },
        survey: { title: "Survey number cross-check", assignedRole: "Outlet Admin", status: "done", completedBy: "Outlet Admin (YOR West)", date: "03 May 2026" },
        encumbrance: { title: "Encumbrance verification", assignedRole: "Outlet Admin", status: "done", completedBy: "Adv. Amit Kulkarni", date: "04 May 2026" },
        ho_signoff: { title: "HO sign-off", assignedRole: "HO Admin", status: "done", completedBy: "Sarah Coleman (HO Admin)", date: "05 May 2026" },
        final_reg: { title: "Final registration entry", assignedRole: "HO Admin", status: "done", completedBy: "Sarah Coleman (HO Admin)", date: "06 May 2026" }
      },
      legalChecklist: {
        "mh_title": { status: "Verified", verifiedBy: "Adv. Amit Kulkarni", date: "03 May 2026", remarks: "30-Year registered conveyance deed verified" },
        "mh_712": { status: "Verified", verifiedBy: "Adv. Amit Kulkarni", date: "03 May 2026", remarks: "Mahabhulekh 7/12 & 8A Extract verified" },
        "mh_search": { status: "Verified", verifiedBy: "Adv. Amit Kulkarni", date: "04 May 2026", remarks: "Sub-Registrar 30-year Search Report Nil Encumbrance" },
        "mh_na": { status: "Verified", verifiedBy: "Adv. Amit Kulkarni", date: "04 May 2026", remarks: "Collector Non-Agricultural (NA) Order verified" },
        "mh_rera": { status: "Verified", verifiedBy: "Adv. Amit Kulkarni", date: "05 May 2026", remarks: "MahaRERA registration certificate verified" }
      }
    },
    {
      id: "PROP-006",
      name: "Capital Boulevard Prime Estate",
      surveyNo: "67/9",
      location: "Golf Course Road, Gurugram",
      state: "Delhi NCR",
      type: "Commercial",
      area: "6,000 sq.ft",
      outlet: "YOR North",
      legalStatus: "In-Review",
      legalStage: "HO sign-off",
      assignedLegalOfficer: "Adv. Neha Sharma",
      submittedBy: "Outlet Admin (YOR North)",
      submittedDate: "05 May 2026",
      valuation: "₹14.2 Cr",
      rawValuation: 142000000,
      valuationHistory: [12.0, 12.8, 13.4, 13.9, 14.2],
      images: 7,
      docsCount: 5,
      active: true,
      firstOwnerInfo: {
        originalOwner: "Ch. Harphool Singh & Descendants",
        acquisitionYear: "1992",
        parentDeedNo: "HR-GGN/DOC-2109/1992",
        sroOffice: "Gurugram Tehsil Sub-Registrar Office",
        extentArea: "6,000 sq.ft (DLF Phase 5 / Golf Course Ext)",
        surveyDemarcation: "Khasra No. 67/9, Wazirabad Revenue Estate, Gurugram",
        khataType: "HSVP / Jamabandi Fard Record #1092",
        parentRemarks: "Original HUDA / HSVP commercial plot auction grant with perpetual commercial land use approval."
      },
      ownershipChain: [
        {
          step: 1,
          date: "18 Aug 1992",
          year: "1992",
          type: "HSVP Allotment & Perpetual Lease",
          seller: "Haryana Urban Development Authority (HUDA)",
          buyer: "Ch. Harphool Singh",
          price: "₹38.0 L",
          rawPrice: 3800000,
          regDocNo: "HR-GGN/1892/1992",
          sro: "Gurugram SRO",
          platform: "Government Auction Allotment",
          agent: "HSVP Allotment Office",
          status: "Archived Parent Deed",
          notes: "Official commercial sector plot allotment with perpetual lease rights."
        },
        {
          step: 2,
          date: "10 May 2019",
          year: "2019",
          type: "First Sale via YOR Platform",
          seller: "Ch. Harphool Singh Legal Heirs",
          buyer: "Apex NCR Realty Ventures Ltd",
          price: "₹8.90 Cr",
          rawPrice: 89000000,
          regDocNo: "SRO/GGN/4102/2019",
          sro: "Gurugram SRO (Book 1, Vol 1022)",
          platform: "YOR Institutional Commercial",
          agent: "Deepak Verma (Urban Crest Real Estate)",
          status: "Registered & Verified",
          notes: "Conveyance deed executed. Pollution Control Board and Fire NOC clearances obtained."
        },
        {
          step: 3,
          date: "14 Nov 2024",
          year: "2024",
          type: "Resale via YOR Platform (Current Owner)",
          seller: "Apex NCR Realty Ventures Ltd",
          buyer: "Capital Boulevard Investment Trust",
          price: "₹14.20 Cr",
          rawPrice: 142000000,
          regDocNo: "SRO/GGN/8890/2024",
          sro: "Gurugram SRO (Book 1, Vol 1560)",
          platform: "YOR Prime Commercial Resale",
          agent: "Vikramaditya Roy (Deccan Prestige Estates)",
          status: "Active Current Title",
          notes: "Present institutional ownership. Pre-leased Grade-A asset with 9.2% net yield. Bank APF clearances from HDFC & ICICI verified."
        }
      ],
      stages: {
        intake: { title: "Document upload & intake", assignedRole: "Outlet Admin", status: "done", completedBy: "Outlet Admin (YOR North)", date: "05 May 2026" },
        survey: { title: "Survey number cross-check", assignedRole: "Outlet Admin", status: "done", completedBy: "Outlet Admin (YOR North)", date: "06 May 2026" },
        encumbrance: { title: "Encumbrance verification", assignedRole: "Outlet Admin", status: "done", completedBy: "Adv. Neha Sharma", date: "07 May 2026" },
        ho_signoff: { title: "HO sign-off", assignedRole: "HO Admin", status: "review", completedBy: "Sarah Coleman (HO Admin)", date: "Pending Final Review" },
        final_reg: { title: "Final registration entry", assignedRole: "HO Admin", status: "pending", completedBy: null, date: "Pending" }
      },
      legalChecklist: {
        "dl_title": { status: "Verified", verifiedBy: "Adv. Neha Sharma", date: "06 May 2026", remarks: "Registered Perpetual Lease Deed with HSVP verified" },
        "dl_conveyance": { status: "Verified", verifiedBy: "Adv. Neha Sharma", date: "06 May 2026", remarks: "Conveyance Deed & Occupation Certificate (OC) verified" },
        "dl_apf": { status: "Verified", verifiedBy: "Adv. Neha Sharma", date: "07 May 2026", remarks: "HDFC, ICICI, Kotak Bank APF Project Sanctions verified" },
        "dl_noc": { status: "Verified", verifiedBy: "Adv. Neha Sharma", date: "07 May 2026", remarks: "Pollution Control Board & Fire Department NOCs verified" },
        "dl_rera": { status: "Under review", verifiedBy: null, date: "08 May 2026", remarks: "HRERA Gurugram Registration certificate under HO audit" }
      }
    }
  ],

  // Multi-State Verification Workflows & Document Requirements (Configurable Engine)
  stateWorkflows: {
    "Karnataka": {
      name: "Karnataka",
      authority: "Department of Stamps and Registration / Bhoomi Revenue Dept",
      portal: "Kaveri 2.0 & Bhoomi Land Records",
      portalUrl: "https://kaveri.karnataka.gov.in",
      searchYears: 30,
      reraPrefix: "K-RERA",
      reraPortal: "https://rera.karnataka.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: true,
      rules: "Mandatory 30-year parent title deed chain, Kaveri 2.0 Form 15 Encumbrance Certificate, Bhoomi RTC extract with mutation register extract.",
      requiredDocs: [
        { id: "ka_title", name: "30-Year Prior Title Deed Chain", category: "Title", mandatory: true, validityYears: 30 },
        { id: "ka_ec", name: "Kaveri 2.0 Encumbrance Certificate (Form 15)", category: "Encumbrance", mandatory: true, validityYears: 30 },
        { id: "ka_rtc", name: "Bhoomi Land Records (RTC / Pahani)", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "ka_mutation", name: "Mutation Extract (MR Copy)", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "ka_zoning", name: "BDA / BMRDA Land-Use & Zoning Clearance", category: "Statutory", mandatory: true, validityYears: 5 },
        { id: "ka_apf", name: "Bank Pre-Loan Sanction (APF Approval)", category: "Clearance", mandatory: false, validityYears: 1 },
        { id: "ka_advocate", name: "Senior Advocate Title Clearance Certificate", category: "Clearance", mandatory: true, validityYears: 1 }
      ]
    },
    "Kerala": {
      name: "Kerala",
      authority: "Kerala Registration Department / Revenue Department",
      portal: "PEARL & e-Rekha Land Records",
      portalUrl: "https://keralaregistration.gov.in",
      searchYears: 20,
      reraPrefix: "K-RERA (Kerala)",
      reraPortal: "https://rera.kerala.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: false,
      rules: "20-year title flow, Thandaper Account & Land Tax receipt, certified EC Form 15, and compliance verification against Kerala Conservation of Paddy Land and Wetland Act.",
      requiredDocs: [
        { id: "kl_title", name: "20-Year Prior Title Deed Flow", category: "Title", mandatory: true, validityYears: 20 },
        { id: "kl_thandaper", name: "Thandaper Extract & Land Tax Receipt", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "kl_ec", name: "Certified Encumbrance Certificate (EC)", category: "Encumbrance", mandatory: true, validityYears: 20 },
        { id: "kl_sketch", name: "Location Sketch & Possession Certificate", category: "Survey", mandatory: true, validityYears: 1 },
        { id: "kl_wetland", name: "Paddy Land & Wetland Act Clearance", category: "Statutory", mandatory: true, validityYears: 5 },
        { id: "kl_rera", name: "K-RERA Registration / Local Body Sanction", category: "Statutory", mandatory: true, validityYears: 5 }
      ]
    },
    "Tamil Nadu": {
      name: "Tamil Nadu",
      authority: "Registration Department, Government of Tamil Nadu",
      portal: "Tnreginet & AnyROR e-Services",
      portalUrl: "https://tnreginet.gov.in",
      searchYears: 30,
      reraPrefix: "TNRERA",
      reraPortal: "https://rera.tn.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: true,
      rules: "30-year parent document chain, Patta/Chitta extraction from AnyROR e-Services, Tnreginet online EC search and DTCP/CMDA layout planning sanctions.",
      requiredDocs: [
        { id: "tn_title", name: "30-Year Parent Document Flow", category: "Title", mandatory: true, validityYears: 30 },
        { id: "tn_patta", name: "e-Services Patta / Chitta Extract", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "tn_ec", name: "Tnreginet Online Encumbrance Certificate", category: "Encumbrance", mandatory: true, validityYears: 30 },
        { id: "tn_dtcp", name: "DTCP / CMDA Approved Layout Permission", category: "Statutory", mandatory: true, validityYears: 5 },
        { id: "tn_apf", name: "Bank Project Approval Letter (APF)", category: "Clearance", mandatory: false, validityYears: 1 }
      ]
    },
    "Maharashtra": {
      name: "Maharashtra",
      authority: "Inspector General of Registration and Controller of Stamps",
      portal: "e-Search (IGR Maharashtra) & Mahabhulekh",
      portalUrl: "https://igrmaharashtra.gov.in",
      searchYears: 30,
      reraPrefix: "MahaRERA",
      reraPortal: "https://maharera.mahaonline.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: true,
      rules: "30-year conveyance chain, Mahabhulekh digitized 7/12 extract with Ferfar (mutation), Collector Non-Agricultural (NA) order and MahaRERA QR verification.",
      requiredDocs: [
        { id: "mh_title", name: "30-Year Registered Conveyance Deed Flow", category: "Title", mandatory: true, validityYears: 30 },
        { id: "mh_712", name: "Mahabhulekh 7/12 & 8A Revenue Extract", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "mh_search", name: "30-Year Title Search & EC Report", category: "Encumbrance", mandatory: true, validityYears: 30 },
        { id: "mh_na", name: "Collector Non-Agricultural (NA) Permission", category: "Statutory", mandatory: true, validityYears: 5 },
        { id: "mh_rera", name: "MahaRERA Project Registration Certificate", category: "Statutory", mandatory: true, validityYears: 5 }
      ]
    },
    "Telangana": {
      name: "Telangana",
      authority: "Registration & Stamps Department Telangana / CCLA",
      portal: "Dharani & IGRS Telangana Portal",
      portalUrl: "https://dharani.telangana.gov.in",
      searchYears: 30,
      reraPrefix: "TSRERA",
      reraPortal: "https://rera.telangana.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: true,
      rules: "Dharani Integrated Land Records passbook verification, 30-year deed search on IGRS, HMDA/GHMC layout sanctions and RERA verification.",
      requiredDocs: [
        { id: "tg_dharani", name: "Dharani Pattadar Passbook & Title Check", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "tg_title", name: "30-Year Registered Sale Deed Chain", category: "Title", mandatory: true, validityYears: 30 },
        { id: "tg_ec", name: "IGRS Telangana Online Encumbrance Certificate", category: "Encumbrance", mandatory: true, validityYears: 30 },
        { id: "tg_hmda", name: "HMDA / GHMC Layout & Building Sanction", category: "Statutory", mandatory: true, validityYears: 5 },
        { id: "tg_apf", name: "Multi-Bank Legal Search & Pre-Sanction", category: "Clearance", mandatory: false, validityYears: 1 }
      ]
    },
    "Andhra Pradesh": {
      name: "Andhra Pradesh",
      authority: "Registration & Stamps Dept / CCLA Andhra Pradesh",
      portal: "Meebhoomi & CARD IGRS AP",
      portalUrl: "https://meebhoomi.ap.gov.in",
      searchYears: 30,
      reraPrefix: "APRERA",
      reraPortal: "https://rera.ap.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: true,
      rules: "Meebhoomi 1B Namoona & Adangal verification, 30-year EC search via IGRS AP, AP CRDA / VMRDA layout approvals.",
      requiredDocs: [
        { id: "ap_meebhoomi", name: "Meebhoomi Adangal & 1B Revenue Record", category: "Revenue", mandatory: true, validityYears: 1 },
        { id: "ap_title", name: "30-Year Prior Title Deed Chain", category: "Title", mandatory: true, validityYears: 30 },
        { id: "ap_ec", name: "IGRS AP Online Encumbrance Certificate", category: "Encumbrance", mandatory: true, validityYears: 30 },
        { id: "ap_crda", name: "AP CRDA / VMRDA Layout Approval", category: "Statutory", mandatory: true, validityYears: 5 }
      ]
    },
    "Delhi NCR": {
      name: "Delhi NCR",
      authority: "Revenue Department Delhi / DDA / Town & Country Planning Haryana",
      portal: "DORIS Delhi & Jamabandi Haryana",
      portalUrl: "https://doris.delhigovt.nic.in",
      searchYears: 30,
      reraPrefix: "HRERA / Delhi RERA",
      reraPortal: "https://haryanarera.gov.in",
      advocateOpinionRequired: true,
      digitalStampRequired: true,
      rules: "Registered Conveyance deed verification, DDA/HSVP allotment and Occupation Certificate (OC), fire NOC and HRERA registration.",
      requiredDocs: [
        { id: "dl_title", name: "Registered Conveyance Deed / Allotment Letter", category: "Title", mandatory: true, validityYears: 30 },
        { id: "dl_conveyance", name: "Occupation Certificate (OC) & Sanction Plan", category: "Statutory", mandatory: true, validityYears: 5 },
        { id: "dl_apf", name: "Nationalized Bank Project Pre-Sanction", category: "Clearance", mandatory: false, validityYears: 1 },
        { id: "dl_noc", name: "Fire & Pollution Department NOCs", category: "Statutory", mandatory: true, validityYears: 3 },
        { id: "dl_rera", name: "HRERA / Delhi RERA Registration", category: "Statutory", mandatory: true, validityYears: 5 }
      ]
    }
  },

  // Document Register linked to Survey Numbers
  documents: [
    { id: "DOC-101", surveyNo: "123/2A", property: "Green Valley Plot", name: "30-Year Sale Deed Chain", version: "v1.2", uploader: "Outlet Admin", status: "Verified", date: "12 May 2026", officer: "Priya Nair", remarks: "30-year flow verified against Sub-Registrar records" },
    { id: "DOC-102", surveyNo: "123/2A", property: "Green Valley Plot", name: "Title Clearance Certificate", version: "v1.0", uploader: "Legal Team", status: "Verified", date: "13 May 2026", officer: "Adv. V. S. Rao", remarks: "Clear marketable title confirmed" },
    { id: "DOC-103", surveyNo: "123/2A", property: "Green Valley Plot", name: "Kaveri 2.0 Nil-Encumbrance Certificate", version: "v1.1", uploader: "Outlet Admin", status: "Verified", date: "12 May 2026", officer: "Priya Nair", remarks: "Form 15 verified from 1996-2026" },
    { id: "DOC-104", surveyNo: "144/3B", property: "Riverside Waterfront Penthouse", name: "20-Year Prior Title Flow", version: "v1.0", uploader: "Outlet Admin", status: "Verified", date: "13 May 2026", officer: "Adv. Rajesh Menon", remarks: "Ernakulam sub-registrar copy verified" },
    { id: "DOC-105", surveyNo: "144/3B", property: "Riverside Waterfront Penthouse", name: "Thandaper & Land Tax Receipt", version: "v1.0", uploader: "Outlet Admin", status: "Verified", date: "13 May 2026", officer: "Adv. Rajesh Menon", remarks: "Kanayannur Taluk roll verified" },
    { id: "DOC-106", surveyNo: "456/38", property: "Cyber Pearl Commercial Tech Park", name: "Dharani Passbook & Survey Map", version: "v1.0", uploader: "Outlet Admin", status: "Resubmit", date: "09 May 2026", officer: "Adv. Suresh Varma", remarks: "Survey number boundary mismatch with Dharani Passbook. Requires revenue demarcation sketch." }
  ],

  // Commission Rules & Agent Payouts
  commissionRules: [
    { id: "CR-1", name: "Standard Property Sale", target: "Residential", rule: "2.5% of net sale price", status: "Active" },
    { id: "CR-2", name: "Luxury Property Tier", target: "Value > ₹5 Cr", rule: "Tiered 2.5–3.0%", status: "Active" },
    { id: "CR-3", name: "Rental Commission", target: "Rental", rule: "1 month rental value", status: "Active" },
    { id: "CR-4", name: "Referral Commission", target: "Agent referral", rule: "1% of net sale price", status: "Scoped" }
  ],

  payouts: [
    { id: "PAY-01", agent: "James Tan", property: "The Lennox Tower", amount: "₹24,500", status: "Paid", date: "Today" },
    { id: "PAY-02", agent: "Sarah Lim", property: "Marina Residences", amount: "₹18,200", status: "Paid", date: "Yesterday" },
    { id: "PAY-03", agent: "Michael Wong", property: "Maple Residences", amount: "₹12,750", status: "Pending", date: "08 Apr" },
    { id: "PAY-04", agent: "Priya Nair", property: "YOR Central", amount: "₹9,600", status: "Approved", date: "05 Apr" }
  ],

  // Rental Listings & Lease Lifecycle (Standard Whole Units & Corporate Leases)
  rentals: [
    {
      id: "RNT-101",
      property: "Riverside Tower 1203",
      outlet: "YOR Central",
      location: "Marine Drive, Kochi, Kerala",
      type: "Individual",
      category: "Luxury Apartment",
      tenant: "Ahmed Al Faisal",
      tenantPhone: "+91 98401 55661",
      tenantEmail: "ahmed.faisal@gmail.com",
      landlord: "Varun Menon (Owner)",
      rent: "₹55,200",
      rawRent: 55200,
      deposit: "₹2,50,000",
      rawDeposit: 250000,
      maintenance: "₹4,500 / mo",
      furnishing: "Fully Furnished",
      bhk: "3 BHK (1,850 sq.ft)",
      leaseStart: "15 Jun 2025",
      leaseEnd: "15 Jun 2027",
      status: "Active",
      appPublished: true,
      appViews: 482,
      appInquiries: 12,
      amenities: ["High-speed WiFi", "Covered Parking", "Clubhouse", "24/7 Security", "Infinity Pool", "Modular Kitchen"],
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
      description: "Ultra-luxury 3 BHK waterfront apartment with panoramic Arabian Sea views, imported Italian marble, and high-end automation."
    },
    {
      id: "RNT-102",
      property: "The Lennox Tower 2801",
      outlet: "YOR South",
      location: "Beach Road, Kozhikode, Kerala",
      type: "Individual",
      category: "Sky Penthouse",
      tenant: "Sarah Michael",
      tenantPhone: "+91 98402 66772",
      tenantEmail: "sarah.m@apexdesign.com",
      landlord: "George Philip (Owner)",
      rent: "₹68,500",
      rawRent: 68500,
      deposit: "₹3,00,000",
      rawDeposit: 300000,
      maintenance: "₹5,200 / mo",
      furnishing: "Fully Furnished",
      bhk: "4 BHK (2,400 sq.ft)",
      leaseStart: "01 Jun 2025",
      leaseEnd: "30 May 2027",
      status: "Active",
      appPublished: true,
      appViews: 615,
      appInquiries: 19,
      amenities: ["Private Terrace", "Smart Home Automation", "Gymnasium", "2 Dedicated EV Slots", "Concierge Service"],
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      description: "Designer 4 BHK sky penthouse featuring 360-degree sea view terrace, double-height ceilings, and private jacuzzi."
    },
    {
      id: "RNT-103",
      property: "Maple Residences B-12",
      outlet: "YOR North",
      location: "Payyambalam, Kannur, Kerala",
      type: "Individual",
      category: "Garden Villa",
      tenant: "Chen Wei",
      tenantPhone: "+91 98403 77883",
      tenantEmail: "chen.wei@globalsupply.sg",
      landlord: "Nasser Al Harthy",
      rent: "₹53,800",
      rawRent: 53800,
      deposit: "₹2,20,000",
      rawDeposit: 220000,
      maintenance: "₹3,800 / mo",
      furnishing: "Semi-Furnished",
      bhk: "3 BHK (2,100 sq.ft)",
      leaseStart: "12 Jul 2025",
      leaseEnd: "12 Jul 2027",
      status: "Active",
      appPublished: true,
      appViews: 298,
      appInquiries: 7,
      amenities: ["Private Lawn", "Gated Security", "Solar Water Heating", "Power Backup", "Car Porch"],
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      description: "Serene standalone garden villa nestled in lush coconut groves with custom landscaped private patio."
    },
    {
      id: "RNT-104",
      property: "YOR Central Tower 901",
      outlet: "YOR Central",
      location: "MG Road, Kochi, Kerala",
      type: "Corporate",
      category: "Commercial Office Floor",
      tenant: "TechNova LLC",
      tenantPhone: "+91 98404 88994",
      tenantEmail: "admin@technova.io",
      landlord: "YOR Estate Assets",
      rent: "₹1,12,000",
      rawRent: 112000,
      deposit: "₹6,00,000",
      rawDeposit: 600000,
      maintenance: "₹12,000 / mo",
      furnishing: "Fully Furnished",
      bhk: "Grade-A Workspace (3,200 sq.ft)",
      leaseStart: "01 May 2024",
      leaseEnd: "01 May 2027",
      status: "Renewal due",
      appPublished: false,
      appViews: 145,
      appInquiries: 3,
      amenities: ["Central HVAC", "Server Room", "Boardroom", "100% DG Backup", "Biometric Access", "High-speed Fiber"],
      image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
      description: "Plug-and-play corporate headquarters setup with 45 workstations, 2 director cabins, and conference suite."
    },
    {
      id: "RNT-105",
      property: "Cedar Business Park 402",
      outlet: "YOR East",
      location: "Baker Junction, Kottayam, Kerala",
      type: "Corporate",
      category: "Commercial Suite",
      tenant: "GlobalTech Solutions",
      tenantPhone: "+91 98405 99005",
      tenantEmail: "facilities@globaltech.com",
      landlord: "Mathew Kurian",
      rent: "₹95,500",
      rawRent: 95500,
      deposit: "₹4,50,000",
      rawDeposit: 450000,
      maintenance: "₹8,500 / mo",
      furnishing: "Fully Furnished",
      bhk: "Executive Office (2,400 sq.ft)",
      leaseStart: "01 Jun 2024",
      leaseEnd: "01 Jun 2027",
      status: "Renewal due",
      appPublished: true,
      appViews: 380,
      appInquiries: 9,
      amenities: ["Reception Lobby", "Cafeteria Access", "Covered Parking", "Fire Safety Sprinklers", "24/7 Security"],
      image: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80",
      description: "Modern commercial office suite strategically situated on main commercial corridor."
    }
  ],

  // Master Lease & Sublease / Hostel / Co-Living Portfolio (Entire flat leased from owner -> Subleased by beds/rooms)
  subleasePortfolios: [
    {
      id: "SUB-001",
      property: "The Lennox Tower - Flat 402",
      outlet: "YOR South",
      location: "Beach Road, Kozhikode, Kerala",
      type: "Hostel / Co-Living Sublease",
      landlord: "Dr. K. Varma (Property Owner)",
      landlordPhone: "+91 98409 11223",
      landlordEmail: "dr.varma@gmail.com",
      masterRent: "₹42,000",
      rawMasterRent: 42000,
      masterDeposit: "₹1,50,000",
      masterLeaseStart: "01 Jan 2026",
      masterLeaseEnd: "31 Dec 2027",
      subleaseNocVerified: true,
      nocDocRef: "NOC-VRM-2026-01",
      utilityExpenseEst: "₹6,500 / mo",
      rawUtility: 6500,
      bhk: "3 BHK (2,050 sq.ft) — 7 Beds",
      totalBeds: 7,
      occupiedBeds: 6,
      vacantBeds: 1,
      subleaseRevenue: "₹75,500",
      rawSubleaseRevenue: 75500,
      netMonthlyMargin: "₹27,000",
      rawMargin: 27000,
      marginRoi: "35.8%",
      appPublished: true,
      targetAudience: "Working Professionals & Postgrad Students",
      amenities: ["High-speed WiFi (300 Mbps)", "Daily Housekeeping", "RO Drinking Water", "Fully Equipped Kitchen", "Washing Machine", "Power Backup", "Biometric Entry"],
      image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
      rooms: [
        {
          id: "R-101",
          name: "Master Suite (Room 1)",
          type: "Twin Sharing (2 Beds)",
          attachedBath: true,
          ac: true,
          beds: [
            { id: "BED-1A", bedNo: "Bed 1A", occupant: "Rahul S. (Software Engineer)", phone: "+91 98401 11221", rent: "₹12,500", rawRent: 12500, deposit: "₹25,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "10 Jan 2026", checkOut: "31 Dec 2026" },
            { id: "BED-1B", bedNo: "Bed 1B", occupant: "Aditya Nair (FinTech Analyst)", phone: "+91 98401 11222", rent: "₹12,500", rawRent: 12500, deposit: "₹25,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "15 Jan 2026", checkOut: "15 Jan 2027" }
          ]
        },
        {
          id: "R-102",
          name: "Deluxe Corner (Room 2)",
          type: "Triple Sharing (3 Beds)",
          attachedBath: true,
          ac: true,
          beds: [
            { id: "BED-2A", bedNo: "Bed 2A", occupant: "Siddharth Menon (Medical Intern)", phone: "+91 98401 11223", rent: "₹9,500", rawRent: 9500, deposit: "₹20,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "01 Feb 2026", checkOut: "31 Jan 2027" },
            { id: "BED-2B", bedNo: "Bed 2B", occupant: "Kiran Joseph (Product Designer)", phone: "+91 98401 11224", rent: "₹9,500", rawRent: 9500, deposit: "₹20,000", status: "Occupied", paymentStatus: "Pending", kycVerified: true, checkIn: "05 Feb 2026", checkOut: "31 Jan 2027" },
            { id: "BED-2C", bedNo: "Bed 2C", occupant: null, phone: null, rent: "₹9,500", rawRent: 9500, deposit: "₹20,000", status: "Vacant", paymentStatus: null, kycVerified: false, checkIn: null, checkOut: null }
          ]
        },
        {
          id: "R-103",
          name: "Balcony Room (Room 3)",
          type: "Twin Sharing (2 Beds)",
          attachedBath: false,
          ac: true,
          beds: [
            { id: "BED-3A", bedNo: "Bed 3A", occupant: "Farhan Ali (Data Scientist)", phone: "+91 98401 11225", rent: "₹11,000", rawRent: 11000, deposit: "₹22,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "20 Jan 2026", checkOut: "20 Jan 2027" },
            { id: "BED-3B", bedNo: "Bed 3B", occupant: "Gautam Shenoy (Consultant)", phone: "+91 98401 11226", rent: "₹11,000", rawRent: 11000, deposit: "₹22,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "01 Feb 2026", checkOut: "31 Jan 2027" }
          ]
        }
      ]
    },
    {
      id: "SUB-002",
      property: "TechHub Executive Residency - Floor 2",
      outlet: "YOR Central",
      location: "Infopark Road, Kakkanad, Kochi, Kerala",
      type: "Hostel / Co-Living Sublease",
      landlord: "Mrs. Preetha Nair (Landlord)",
      landlordPhone: "+91 98409 33445",
      landlordEmail: "preetha.nair@outlook.com",
      masterRent: "₹65,000",
      rawMasterRent: 65000,
      masterDeposit: "₹2,50,000",
      masterLeaseStart: "01 Nov 2025",
      masterLeaseEnd: "31 Oct 2027",
      subleaseNocVerified: true,
      nocDocRef: "NOC-PTR-2025-09",
      utilityExpenseEst: "₹12,000 / mo",
      rawUtility: 12000,
      bhk: "4 BHK Penthouse (2,900 sq.ft) — 10 Beds",
      totalBeds: 10,
      occupiedBeds: 9,
      vacantBeds: 1,
      subleaseRevenue: "₹1,18,000",
      rawSubleaseRevenue: 118000,
      netMonthlyMargin: "₹41,000",
      rawMargin: 41000,
      marginRoi: "34.7%",
      appPublished: true,
      targetAudience: "IT & Tech Professionals",
      amenities: ["Dedicated Workspace with Ergonomic Chairs", "1 Gbps Dual Fiber", "Daily Breakfast & Dinner Mess", "Gym & Recreation Room", "Housekeeping", "24/7 Security"],
      image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
      rooms: [
        {
          id: "R-201",
          name: "Executive Suite A",
          type: "Twin Sharing (2 Beds)",
          attachedBath: true,
          ac: true,
          beds: [
            { id: "BED-4A", bedNo: "Bed A1", occupant: "Vikas Pillai (Cloud Architect)", phone: "+91 98401 22331", rent: "₹14,000", rawRent: 14000, deposit: "₹28,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "01 Dec 2025", checkOut: "30 Nov 2026" },
            { id: "BED-4B", bedNo: "Bed A2", occupant: "Tariq Mansoor (AI Engineer)", phone: "+91 98401 22332", rent: "₹14,000", rawRent: 14000, deposit: "₹28,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "05 Dec 2025", checkOut: "30 Nov 2026" }
          ]
        },
        {
          id: "R-202",
          name: "Executive Suite B",
          type: "Twin Sharing (2 Beds)",
          attachedBath: true,
          ac: true,
          beds: [
            { id: "BED-5A", bedNo: "Bed B1", occupant: "Anand R. (DevOps Lead)", phone: "+91 98401 22333", rent: "₹13,500", rawRent: 13500, deposit: "₹27,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "10 Dec 2025", checkOut: "09 Dec 2026" },
            { id: "BED-5B", bedNo: "Bed B2", occupant: "Saurav Sen (Security Engineer)", phone: "+91 98401 22334", rent: "₹13,500", rawRent: 13500, deposit: "₹27,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "15 Dec 2025", checkOut: "14 Dec 2026" }
          ]
        },
        {
          id: "R-203",
          name: "Standard Shared Wing",
          type: "Triple Sharing (3 Beds)",
          attachedBath: false,
          ac: true,
          beds: [
            { id: "BED-6A", bedNo: "Bed C1", occupant: "Manoj Kumar (Backend Dev)", phone: "+91 98401 22335", rent: "₹11,000", rawRent: 11000, deposit: "₹22,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "01 Jan 2026", checkOut: "31 Dec 2026" },
            { id: "BED-6B", bedNo: "Bed C2", occupant: "Nikhil George (QA Lead)", phone: "+91 98401 22336", rent: "₹11,000", rawRent: 11000, deposit: "₹22,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "05 Jan 2026", checkOut: "31 Dec 2026" },
            { id: "BED-6C", bedNo: "Bed C3", occupant: null, phone: null, rent: "₹11,000", rawRent: 11000, deposit: "₹22,000", status: "Vacant", paymentStatus: null, kycVerified: false, checkIn: null, checkOut: null }
          ]
        },
        {
          id: "R-204",
          name: "Studio Pod Room",
          type: "Triple Sharing (3 Beds)",
          attachedBath: true,
          ac: true,
          beds: [
            { id: "BED-7A", bedNo: "Bed D1", occupant: "Rohit Varma (Product Manager)", phone: "+91 98401 22337", rent: "₹12,000", rawRent: 12000, deposit: "₹24,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "12 Jan 2026", checkOut: "11 Jan 2027" },
            { id: "BED-7B", bedNo: "Bed D2", occupant: "Jayakrishnan (Data Analyst)", phone: "+91 98401 22338", rent: "₹12,000", rawRent: 12000, deposit: "₹24,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "15 Jan 2026", checkOut: "14 Jan 2027" },
            { id: "BED-7C", bedNo: "Bed D3", occupant: "Harish Patel (FinTech Dev)", phone: "+91 98401 22339", rent: "₹12,000", rawRent: 12000, deposit: "₹24,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "20 Jan 2026", checkOut: "19 Jan 2027" }
          ]
        }
      ]
    },
    {
      id: "SUB-003",
      property: "Greenway Luxury Villa Suite",
      outlet: "YOR West",
      location: "Munnar Road, Idukki, Kerala",
      type: "Hostel / Co-Living Sublease",
      landlord: "Mr. Roy Chacko (Owner)",
      landlordPhone: "+91 98409 55667",
      landlordEmail: "roy.chacko@teaestates.in",
      masterRent: "₹38,000",
      rawMasterRent: 38000,
      masterDeposit: "₹1,20,000",
      masterLeaseStart: "01 Jan 2026",
      masterLeaseEnd: "31 Dec 2027",
      subleaseNocVerified: true,
      nocDocRef: "NOC-RC-2026-03",
      utilityExpenseEst: "₹5,500 / mo",
      rawUtility: 5500,
      bhk: "3 BHK Mountain Villa (2,200 sq.ft) — 6 Beds",
      totalBeds: 6,
      occupiedBeds: 4,
      vacantBeds: 2,
      subleaseRevenue: "₹62,000",
      rawSubleaseRevenue: 62000,
      netMonthlyMargin: "₹18,500",
      rawMargin: 18500,
      marginRoi: "29.8%",
      appPublished: true,
      targetAudience: "Remote Professionals & Digital Nomads",
      amenities: ["Mountain View Deck", "High-speed Starlink WiFi", "Power Backup", "Fireplace Lounge", "Daily Housekeeping", "Organic Veg Breakfast"],
      image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
      rooms: [
        {
          id: "R-301",
          name: "Panoramic View Suite",
          type: "Twin Sharing (2 Beds)",
          attachedBath: true,
          ac: true,
          beds: [
            { id: "BED-8A", bedNo: "Bed V1", occupant: "Neil Armstrong (Digital Marketer)", phone: "+91 98401 33441", rent: "₹12,000", rawRent: 12000, deposit: "₹24,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "10 Feb 2026", checkOut: "10 Aug 2026" },
            { id: "BED-8B", bedNo: "Bed V2", occupant: "Sana Farooq (UI Designer)", phone: "+91 98401 33442", rent: "₹12,000", rawRent: 12000, deposit: "₹24,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "15 Feb 2026", checkOut: "15 Aug 2026" }
          ]
        },
        {
          id: "R-302",
          name: "Tea Garden Room",
          type: "Twin Sharing (2 Beds)",
          attachedBath: true,
          ac: false,
          beds: [
            { id: "BED-9A", bedNo: "Bed T1", occupant: "Devika Unni (Travel Writer)", phone: "+91 98401 33443", rent: "₹10,000", rawRent: 10000, deposit: "₹20,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "01 Mar 2026", checkOut: "31 Aug 2026" },
            { id: "BED-9B", bedNo: "Bed T2", occupant: "Abhishek S. (App Developer)", phone: "+91 98401 33444", rent: "₹10,000", rawRent: 10000, deposit: "₹20,000", status: "Occupied", paymentStatus: "Paid", kycVerified: true, checkIn: "01 Mar 2026", checkOut: "31 Aug 2026" }
          ]
        },
        {
          id: "R-303",
          name: "Forest Cottage Room",
          type: "Twin Sharing (2 Beds)",
          attachedBath: false,
          ac: false,
          beds: [
            { id: "BED-10A", bedNo: "Bed F1", occupant: null, phone: null, rent: "₹9,000", rawRent: 9000, deposit: "₹18,000", status: "Vacant", paymentStatus: null, kycVerified: false, checkIn: null, checkOut: null },
            { id: "BED-10B", bedNo: "Bed F2", occupant: null, phone: null, rent: "₹9,000", rawRent: 9000, deposit: "₹18,000", status: "Vacant", paymentStatus: null, kycVerified: false, checkIn: null, checkOut: null }
          ]
        }
      ]
    }
  ],

  // End Customers Inquiries from YOR Estate Mobile App
  rentalInquiries: [
    {
      id: "INQ-201",
      customerName: "Aarav Sharma",
      phone: "+91 98408 12345",
      email: "aarav.sharma@accenture.com",
      requestedProperty: "The Lennox Tower - Flat 402",
      requestedUnitType: "Hostel Bed (Deluxe Corner Room 2)",
      budget: "₹9,500 / mo",
      moveInDate: "May 1, 2026",
      source: "iOS Mobile App",
      status: "New",
      message: "Hi, I am joining Infopark next month and looking for a single bed in a premium shared flat with WiFi and food options.",
      assignedAgent: "Sarah Coleman",
      createdAt: "Today, 10:30 AM"
    },
    {
      id: "INQ-202",
      customerName: "Meera Nambiar",
      phone: "+91 98408 23456",
      email: "meera.n@kpmg.com",
      requestedProperty: "Riverside Tower 1203",
      requestedUnitType: "Whole 3 BHK Apartment",
      budget: "₹55,000 / mo",
      moveInDate: "May 15, 2026",
      source: "Android Mobile App",
      status: "Tour Scheduled",
      tourTime: "Tomorrow, 4:30 PM",
      message: "Looking for immediate family occupancy. Want to inspect the sea view balcony and clubhouse amenities.",
      assignedAgent: "Arjun Mehta",
      createdAt: "Yesterday, 3:15 PM"
    },
    {
      id: "INQ-203",
      customerName: "Karthik Raja",
      phone: "+91 98408 34567",
      email: "karthik.r@zomato.in",
      requestedProperty: "TechHub Executive Residency",
      requestedUnitType: "Hostel Bed (Standard Shared Wing)",
      budget: "₹11,000 / mo",
      moveInDate: "Immediate",
      source: "Android Mobile App",
      status: "Offer Received",
      message: "Ready to pay 2 months advance deposit today. Please confirm if AC & food mess are included.",
      assignedAgent: "Rahul Nair",
      createdAt: "28 Apr 2026"
    },
    {
      id: "INQ-204",
      customerName: "Pooja Hegde",
      phone: "+91 98408 45678",
      email: "pooja.hegde@deloitte.com",
      requestedProperty: "Greenway Luxury Villa Suite",
      requestedUnitType: "Co-Living Bed (Forest Room)",
      budget: "₹9,000 / mo",
      moveInDate: "May 10, 2026",
      source: "iOS Mobile App",
      status: "Agreement Sent",
      message: "Remote worker looking for 6 months quiet stay with high-speed internet in Munnar/Idukki.",
      assignedAgent: "May Lim",
      createdAt: "27 Apr 2026"
    },
    {
      id: "INQ-205",
      customerName: "Dr. Sandeep Thomas",
      phone: "+91 98408 56789",
      email: "dr.sandeep@aims.edu",
      requestedProperty: "The Lennox Tower 2801",
      requestedUnitType: "Whole 4 BHK Penthouse",
      budget: "₹68,000 / mo",
      moveInDate: "Jun 1, 2026",
      source: "iOS Mobile App",
      status: "Converted",
      message: "Signed agreement for 2-year lease term. Security deposit of ₹3,00,000 transferred via RTGS.",
      assignedAgent: "Sarah Coleman",
      createdAt: "24 Apr 2026"
    }
  ],

  // Rent Roll & Monthly Collection Ledger
  rentRoll: [
    {
      id: "RR-501",
      tenantName: "Ahmed Al Faisal",
      property: "Riverside Tower 1203",
      unitOrBed: "Unit 1203 (3 BHK)",
      type: "Whole Unit Lease",
      dueAmount: "₹55,200",
      rawDue: 55200,
      dueDate: "05 May 2026",
      paidAmount: "₹55,200",
      rawPaid: 55200,
      paymentDate: "03 May 2026",
      paymentMode: "UPI / PhonePe",
      receiptNo: "RCPT-2026-0501",
      status: "Paid"
    },
    {
      id: "RR-502",
      tenantName: "Sarah Michael",
      property: "The Lennox Tower 2801",
      unitOrBed: "Penthouse 2801 (4 BHK)",
      type: "Whole Unit Lease",
      dueAmount: "₹68,500",
      rawDue: 68500,
      dueDate: "05 May 2026",
      paidAmount: "₹68,500",
      rawPaid: 68500,
      paymentDate: "02 May 2026",
      paymentMode: "NEFT / HDFC Bank",
      receiptNo: "RCPT-2026-0502",
      status: "Paid"
    },
    {
      id: "RR-503",
      tenantName: "Rahul S.",
      property: "The Lennox Tower - Flat 402",
      unitOrBed: "Room 1 - Bed 1A",
      type: "Sublease Hostel Bed",
      dueAmount: "₹12,500",
      rawDue: 12500,
      dueDate: "05 May 2026",
      paidAmount: "₹12,500",
      rawPaid: 12500,
      paymentDate: "04 May 2026",
      paymentMode: "Google Pay UPI",
      receiptNo: "RCPT-2026-0503",
      status: "Paid"
    },
    {
      id: "RR-504",
      tenantName: "Aditya Nair",
      property: "The Lennox Tower - Flat 402",
      unitOrBed: "Room 1 - Bed 1B",
      type: "Sublease Hostel Bed",
      dueAmount: "₹12,500",
      rawDue: 12500,
      dueDate: "05 May 2026",
      paidAmount: "₹12,500",
      rawPaid: 12500,
      paymentDate: "01 May 2026",
      paymentMode: "UPI",
      receiptNo: "RCPT-2026-0504",
      status: "Paid"
    },
    {
      id: "RR-505",
      tenantName: "Kiran Joseph",
      property: "The Lennox Tower - Flat 402",
      unitOrBed: "Room 2 - Bed 2B",
      type: "Sublease Hostel Bed",
      dueAmount: "₹9,500",
      rawDue: 9500,
      dueDate: "05 May 2026",
      paidAmount: "₹0",
      rawPaid: 0,
      paymentDate: "-",
      paymentMode: "Pending",
      receiptNo: "-",
      status: "Pending Verification"
    },
    {
      id: "RR-506",
      tenantName: "TechNova LLC",
      property: "YOR Central Tower 901",
      unitOrBed: "Suite 901 (Commercial)",
      type: "Corporate Lease",
      dueAmount: "₹1,12,000",
      rawDue: 112000,
      dueDate: "01 May 2026",
      paidAmount: "₹1,12,000",
      rawPaid: 112000,
      paymentDate: "29 Apr 2026",
      paymentMode: "RTGS / ICICI",
      receiptNo: "RCPT-2026-0505",
      status: "Paid"
    },
    {
      id: "RR-507",
      tenantName: "GlobalTech Solutions",
      property: "Cedar Business Park 402",
      unitOrBed: "Suite 402 (Commercial)",
      type: "Corporate Lease",
      dueAmount: "₹95,500",
      rawDue: 95500,
      dueDate: "01 May 2026",
      paidAmount: "₹0",
      rawPaid: 0,
      paymentDate: "-",
      paymentMode: "Cheque in clearing",
      receiptNo: "-",
      status: "Overdue"
    }
  ],

  // Group Investments & Co-Investor Mapping (4-5 per property)
  investments: [
    {
      id: "INV-001",
      property: "Riverside Tower",
      type: "Commercial",
      invested: "₹2.50 Cr",
      investorCount: 5,
      projectedRoi: "12.0%",
      lockPeriod: "24 months",
      lockRemaining: "18 months",
      status: "Active",
      coInvestors: [
        { name: "Tan Wei Ming (You)", share: 35 },
        { name: "Ayesha Capital", share: 25 },
        { name: "Family Office Trust", share: 20 },
        { name: "Private Syndicate", share: 20 }
      ]
    },
    {
      id: "INV-002",
      property: "Maple Residences",
      type: "Residential",
      invested: "₹1.80 Cr",
      investorCount: 4,
      projectedRoi: "10.5%",
      lockPeriod: "36 months",
      lockRemaining: "28 months",
      status: "Active",
      coInvestors: [
        { name: "Tan Wei Ming (You)", share: 40 },
        { name: "Nexus Equity", share: 30 },
        { name: "Dr. K. Sharma", share: 15 },
        { name: "Meera Iyer", share: 15 }
      ]
    },
    {
      id: "INV-003",
      property: "Cedar Business Park",
      type: "Mixed use",
      invested: "₹3.20 Cr",
      investorCount: 5,
      projectedRoi: "14.2%",
      lockPeriod: "24 months",
      lockRemaining: "12 months",
      status: "Review",
      coInvestors: [
        { name: "Tan Wei Ming (You)", share: 20 },
        { name: "Aria Ventures", share: 30 },
        { name: "Horizon Wealth", share: 25 },
        { name: "Zenith Holdings", share: 25 }
      ]
    }
  ],

  // Sales CRM Pipeline
  leads: [
    { id: "L-1", name: "Ahmad Rahman", property: "The Imperial Azure Penthouse", outlet: "YOR Central", stage: "New", budget: "₹8.75 Cr", rawBudget: 8.75, phone: "+91 98401 22334", email: "ahmad.r@gmail.com", assigned: "Sarah Coleman", priority: "High", source: "Website Direct", nextTask: { id: "T-1", title: "Site visit confirmation & survey layout map sharing", due: "Today, 4:00 PM", type: "Site Visit", done: false }, notes: "HNW buyer looking for penthouse in Lavelle Road.", createdAt: "2026-04-28" },
    { id: "L-2", name: "Priya Nair", property: "Palm Villa Jumeirah", outlet: "YOR Central", stage: "New", budget: "₹3.2 Cr", rawBudget: 3.2, phone: "+91 98402 33445", email: "priya.nair@outlook.com", assigned: "Arjun Mehta", priority: "Medium", source: "Referral", nextTask: { id: "T-2", title: "Send digital brochure & Kaveri EC extract", due: "Tomorrow, 11:00 AM", type: "Email", done: false }, notes: "Interested in 3 BHK gated community near Indiranagar.", createdAt: "2026-04-27" },
    { id: "L-3", name: "Omar Khalid", property: "Commercial Complex Hub", outlet: "YOR South", stage: "New", budget: "₹4.5 Cr", rawBudget: 4.5, phone: "+91 98403 44556", email: "omar.khalid@emirates.com", assigned: "Rahul Nair", priority: "High", source: "Walk-in Branch", nextTask: { id: "T-3", title: "Discuss pre-leased rental yield terms", due: "May 2, 2:30 PM", type: "Call", done: false }, notes: "NRI investor evaluating Grade-A office floor with 8.5% yield.", createdAt: "2026-04-26" },
    { id: "L-4", name: "Daniel Cheong", property: "The Lennox Tower", outlet: "YOR South", stage: "Followed Up", budget: "₹2.1 Cr", rawBudget: 2.1, phone: "+91 98404 55667", email: "daniel.c@singtel.com", assigned: "Riyas Ali", priority: "Medium", source: "Channel Partner / Agent", nextTask: { id: "T-4", title: "Second site walkthrough with family", due: "May 3, 10:00 AM", type: "Site Visit", done: false }, notes: "Completed first round inquiry. Follow-up meeting scheduled.", createdAt: "2026-04-24" },
    { id: "L-5", name: "Fatima Al Mansoori", property: "Forest Ridge Luxury Villa", outlet: "YOR North", stage: "Followed Up", budget: "₹4.85 Cr", rawBudget: 4.85, phone: "+91 98405 66778", email: "fatima.mansoori@gov.ae", assigned: "Siti Rahman", priority: "High", source: "Instagram / Ad Campaign", nextTask: { id: "T-5", title: "Verify APF bank loan eligibility from HDFC", due: "Today, 5:30 PM", type: "Task", done: false }, notes: "Looking for ready-to-move luxury home with infinity pool.", createdAt: "2026-04-22" },
    { id: "L-6", name: "Emily Carter", property: "Riverside Tower", outlet: "YOR North", stage: "Followed Up", budget: "₹1.8 Cr", rawBudget: 1.8, phone: "+91 98406 77889", email: "emily.carter@globalreach.org", assigned: "Kevin Rao", priority: "Low", source: "Website Direct", nextTask: { id: "T-6", title: "Follow up on negotiation counter-offer", due: "Tomorrow, 3:00 PM", type: "Call", done: true }, notes: "Requested floor plan modifications for 3 BHK corner unit.", createdAt: "2026-04-20" },
    { id: "L-7", name: "Ryan Teo", property: "Marina Luxury Residences", outlet: "YOR West", stage: "Negotiation", budget: "₹5.5 Cr", rawBudget: 5.5, phone: "+91 98407 88990", email: "ryan.teo@apexcapital.sg", assigned: "Daniel Lee", priority: "High", source: "Referral", nextTask: { id: "T-7", title: "Draft token advance agreement with legal team", due: "Today, 6:00 PM", type: "Meeting", done: false }, notes: "Offer submitted at ₹5.35 Cr, owner agreed in principle.", createdAt: "2026-04-18" },
    { id: "L-8", name: "Lucas Martin", property: "Commercial Unit 402", outlet: "YOR West", stage: "Negotiation", budget: "₹2.8 Cr", rawBudget: 2.8, phone: "+91 98408 99001", assigned: "Daniel Lee", email: "lucas.m@techcorp.io", priority: "Medium", source: "Walk-in Branch", nextTask: { id: "T-8", title: "Review stamp duty calculations and tax invoice", due: "May 4, 11:30 AM", type: "Task", done: false }, notes: "Final commercial lease-purchase terms under legal review.", createdAt: "2026-04-15" },
    { id: "L-9", name: "Aisha Rahman", property: "Townhouse - Aria", outlet: "YOR East", stage: "Negotiation", budget: "₹1.9 Cr", rawBudget: 1.9, phone: "+91 98409 00112", email: "aisha.r@investments.com", assigned: "May Lim", priority: "High", source: "Instagram / Ad Campaign", nextTask: { id: "T-9", title: "Negotiation final review with Branch Manager", due: "Today, 3:00 PM", type: "Meeting", done: false }, notes: "Requested parking bay allocation and clubhouse membership waiver.", createdAt: "2026-04-12" },
    { id: "L-10", name: "James Lee", property: "Maple Residences", outlet: "YOR Central", stage: "Converted", budget: "₹1.2 Cr", rawBudget: 1.2, phone: "+91 98410 11223", email: "james.lee@consulting.com", assigned: "Sarah Coleman", priority: "High", source: "Website Direct", nextTask: { id: "T-10", title: "Sale deed registration completed", due: "Completed", type: "Deed", done: true }, notes: "Full payment received and possession key handed over.", createdAt: "2026-04-10" },
    { id: "L-11", name: "Sarah Lim", property: "Cedar Business Park", outlet: "YOR Central", stage: "Converted", budget: "₹3.0 Cr", rawBudget: 3.0, phone: "+91 98411 22334", email: "sarah.lim@logistics.com", assigned: "Arjun Mehta", priority: "High", source: "Referral", nextTask: { id: "T-11", title: "Handover inspection sign-off", due: "Completed", type: "Deed", done: true }, notes: "Commercial office space booked with ₹50L token advance.", createdAt: "2026-04-05" },
    { id: "L-12", name: "Luca Bianchi", property: "Office Unit 12B", outlet: "YOR North", stage: "Dropped", budget: "₹60 L", rawBudget: 0.6, phone: "+91 98412 33445", email: "luca.b@design.it", assigned: "Siti Rahman", priority: "Low", source: "Website Direct", nextTask: null, notes: "Client postponed investment indefinitely due to budget constraints.", createdAt: "2026-03-28" },
    { id: "L-13", name: "David Smith", property: "Retail Unit Corner", outlet: "YOR East", stage: "Dropped", budget: "₹85 L", rawBudget: 0.85, phone: "+91 98413 44556", email: "david.smith@retail.uk", assigned: "May Lim", priority: "Low", source: "Walk-in Branch", nextTask: null, notes: "Selected alternative commercial location.", createdAt: "2026-03-25" }
  ],

  // Finance Team Cross-Outlet Ledger
  financeLedger: [
    { id: "TX-901", date: "28 Apr", desc: "Office rental income", outlet: "YOR Central", type: "Income", amount: "₹12.00 L", rawAmount: 1200000, status: "Received" },
    { id: "TX-902", date: "27 Apr", desc: "Property management fee", outlet: "Marina", type: "Income", amount: "₹5.20 L", rawAmount: 520000, status: "Received" },
    { id: "TX-903", date: "26 Apr", desc: "Marketing expense", outlet: "Head Office", type: "Expense", amount: "-₹3.45 L", rawAmount: -345000, status: "Paid" },
    { id: "TX-904", date: "25 Apr", desc: "Commission payout", outlet: "Sales Team", type: "Expense", amount: "-₹18.20 L", rawAmount: -1820000, status: "Approval" },
    { id: "TX-905", date: "22 Apr", desc: "Rental income", outlet: "Riverside", type: "Income", amount: "₹7.20 L", rawAmount: 720000, status: "Received" }
  ],

  // Agents & External Brokers Network (Non-exclusive, Multi-Outlet Hub Coverage)
  agents: [
    {
      id: "AG-101",
      name: "Sarah Lim",
      agency: "Apex Luxury Realtors",
      type: "Channel Partner",
      tier: "Platinum",
      reraNo: "PRM/KA/RERA/1251/310/AG/210518/002194",
      outlets: ["YOR South", "YOR Central", "YOR West"],
      outlet: "Multi-Hub (South, Central, West)",
      city: "Bengaluru",
      state: "Karnataka",
      phone: "+91 98450 12890",
      email: "sarah.lim@apexrealty.com",
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Ultra-Luxury Villas & Plots",
      commissionRate: "2.5%",
      propertiesConnected: [
        { id: "PROP-001", name: "Green Valley Plot", surveyNo: "123/2A", valuation: "₹12.5 Cr", location: "Devenahalli, Bengaluru", outlet: "YOR South", state: "Karnataka", type: "Land" },
        { id: "PROP-004", name: "Marina Sea Breeze Residences", surveyNo: "90/4", valuation: "₹18.6 Cr", location: "OMR, Chennai", outlet: "YOR South", state: "Tamil Nadu", type: "Residential" },
        { id: "PROP-005", name: "The Lennox Luxury Penthouse", surveyNo: "221/11A", valuation: "₹32.0 Cr", location: "Worli, Mumbai", outlet: "YOR West", state: "Maharashtra", type: "Residential" }
      ],
      activeLeads: 18,
      dealsClosed: 28,
      totalSalesVolume: "₹63.1 Cr",
      rawSalesVolume: 631000000,
      totalCommissionEarned: "₹28.64 L",
      rawCommissionEarned: 2864000,
      commissionPaid: "₹22.40 L",
      rawCommissionPaid: 2240000,
      commissionPending: "₹6.24 L",
      rawCommissionPending: 624000,
      rating: 4.9,
      joinedDate: "14 Jan 2024",
      bankDetails: { bank: "HDFC Bank", acc: "•••• •••• 8821", ifsc: "HDFC0001234", upi: "sarahlim@okhdfcbank" },
      recentPayouts: [
        { id: "PAY-02", date: "24 Apr 2026", amount: "₹4.80 L", property: "The Lennox Luxury Penthouse", status: "Paid" },
        { id: "PAY-11", date: "10 Mar 2026", amount: "₹6.20 L", property: "Green Valley Plot", status: "Paid" },
        { id: "PAY-19", date: "02 May 2026", amount: "₹3.12 L", property: "Marina Sea Breeze Residences", status: "Pending" }
      ]
    },
    {
      id: "AG-102",
      name: "James Tan",
      agency: "Prime Horizon Realty",
      type: "Channel Partner",
      tier: "Platinum",
      reraNo: "K-RERA/AG/0045/2021",
      outlets: ["YOR Central", "YOR South", "YOR East"],
      outlet: "Multi-Hub (Central, South, East)",
      city: "Kochi",
      state: "Kerala",
      phone: "+91 98460 23456",
      email: "james.tan@primehorizon.in",
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Waterfront Penthouses & Estates",
      commissionRate: "2.5%",
      propertiesConnected: [
        { id: "PROP-002", name: "Riverside Waterfront Penthouse", surveyNo: "144/3B", valuation: "₹8.4 Cr", location: "Marine Drive, Kochi", outlet: "YOR Central", state: "Kerala", type: "Residential" },
        { id: "PROP-003", name: "Cyber Pearl Commercial Tech Park", surveyNo: "456/38", valuation: "₹25.0 Cr", location: "HITEC City, Hyderabad", outlet: "YOR Central", state: "Telangana", type: "Commercial" }
      ],
      activeLeads: 12,
      dealsClosed: 22,
      totalSalesVolume: "₹41.8 Cr",
      rawSalesVolume: 418000000,
      totalCommissionEarned: "₹19.40 L",
      rawCommissionEarned: 1940000,
      commissionPaid: "₹18.00 L",
      rawCommissionPaid: 1800000,
      commissionPending: "₹1.40 L",
      rawCommissionPending: 140000,
      rating: 4.8,
      joinedDate: "20 Mar 2024",
      bankDetails: { bank: "ICICI Bank", acc: "•••• •••• 4519", ifsc: "ICIC0000104", upi: "jamestan@okicici" },
      recentPayouts: [
        { id: "PAY-01", date: "Today", amount: "₹2.45 L", property: "Riverside Waterfront Penthouse", status: "Paid" },
        { id: "PAY-14", date: "15 Apr 2026", amount: "₹4.50 L", property: "Cyber Pearl Commercial Tech Park", status: "Paid" }
      ]
    },
    {
      id: "AG-103",
      name: "Vikramaditya Roy",
      agency: "Deccan Prestige Estates",
      type: "Agency Partner",
      tier: "Gold",
      reraNo: "TG/RERA/AG/11902/2022",
      outlets: ["YOR Central", "YOR North"],
      outlet: "Multi-Hub (Central, North)",
      city: "Hyderabad",
      state: "Telangana",
      phone: "+91 98471 34567",
      email: "vikram.roy@deccanprestige.com",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Tech Corridors & Grade-A Office Floors",
      commissionRate: "2.5%",
      propertiesConnected: [
        { id: "PROP-003", name: "Cyber Pearl Commercial Tech Park", surveyNo: "456/38", valuation: "₹25.0 Cr", location: "HITEC City, Hyderabad", outlet: "YOR Central", state: "Telangana", type: "Commercial" },
        { id: "PROP-006", name: "Capital Boulevard Prime Estate", surveyNo: "67/9", valuation: "₹14.2 Cr", location: "Golf Course Road, Gurugram", outlet: "YOR North", state: "Delhi NCR", type: "Commercial" }
      ],
      activeLeads: 14,
      dealsClosed: 16,
      totalSalesVolume: "₹29.2 Cr",
      rawSalesVolume: 292000000,
      totalCommissionEarned: "₹14.50 L",
      rawCommissionEarned: 1450000,
      commissionPaid: "₹11.20 L",
      rawCommissionPaid: 1120000,
      commissionPending: "₹3.30 L",
      rawCommissionPending: 330000,
      rating: 4.8,
      joinedDate: "10 Jun 2024",
      bankDetails: { bank: "Axis Bank", acc: "•••• •••• 9934", ifsc: "UTIB0000058", upi: "vikramroy@axisbank" },
      recentPayouts: [
        { id: "PAY-18", date: "18 Apr 2026", amount: "₹3.20 L", property: "Cyber Pearl Commercial Tech Park", status: "Paid" },
        { id: "PAY-21", date: "28 Apr 2026", amount: "₹3.30 L", property: "Capital Boulevard Prime Estate", status: "Pending" }
      ]
    },
    {
      id: "AG-104",
      name: "Ananya Sharma",
      agency: "Skyline Channel Partners",
      type: "Channel Partner",
      tier: "Gold",
      reraNo: "PRM/KA/RERA/1251/310/AG/220811/003892",
      outlets: ["YOR South", "YOR Central"],
      outlet: "Multi-Hub (South, Central)",
      city: "Bengaluru",
      state: "Karnataka",
      phone: "+91 98482 45678",
      email: "ananya@skylinepartners.in",
      photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Gated Enclaves & Tech Community Condos",
      commissionRate: "2.5%",
      propertiesConnected: [
        { id: "PROP-001", name: "Green Valley Plot", surveyNo: "123/2A", valuation: "₹12.5 Cr", location: "Devenahalli, Bengaluru", outlet: "YOR South", state: "Karnataka", type: "Land" },
        { id: "PROP-004", name: "Marina Sea Breeze Residences", surveyNo: "90/4", valuation: "₹18.6 Cr", location: "OMR, Chennai", outlet: "YOR South", state: "Tamil Nadu", type: "Residential" }
      ],
      activeLeads: 9,
      dealsClosed: 12,
      totalSalesVolume: "₹19.6 Cr",
      rawSalesVolume: 196000000,
      totalCommissionEarned: "₹9.80 L",
      rawCommissionEarned: 980000,
      commissionPaid: "₹8.50 L",
      rawCommissionPaid: 850000,
      commissionPending: "₹1.30 L",
      rawCommissionPending: 130000,
      rating: 4.7,
      joinedDate: "15 Aug 2024",
      bankDetails: { bank: "Kotak Mahindra Bank", acc: "•••• •••• 7712", ifsc: "KKBK0000421", upi: "ananyasharma@okaxis" },
      recentPayouts: [
        { id: "PAY-08", date: "22 Mar 2026", amount: "₹2.50 L", property: "Green Valley Plot", status: "Paid" }
      ]
    },
    {
      id: "AG-105",
      name: "Mohammed Farooq",
      agency: "Malabar Realty Group",
      type: "Independent Broker",
      tier: "Gold",
      reraNo: "K-RERA/AG/0112/2022",
      outlets: ["YOR South", "YOR Central", "YOR East"],
      outlet: "Multi-Hub (South, Central, East)",
      city: "Kozhikode",
      state: "Kerala",
      phone: "+91 98493 56789",
      email: "farooq@malabarrealty.com",
      photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "NRI Luxury Residential & Heritage Estates",
      commissionRate: "2.5%",
      propertiesConnected: [
        { id: "PROP-002", name: "Riverside Waterfront Penthouse", surveyNo: "144/3B", valuation: "₹8.4 Cr", location: "Marine Drive, Kochi", outlet: "YOR Central", state: "Kerala", type: "Residential" }
      ],
      activeLeads: 8,
      dealsClosed: 14,
      totalSalesVolume: "₹22.4 Cr",
      rawSalesVolume: 224000000,
      totalCommissionEarned: "₹11.20 L",
      rawCommissionEarned: 1120000,
      commissionPaid: "₹9.80 L",
      rawCommissionPaid: 980000,
      commissionPending: "₹1.40 L",
      rawCommissionPending: 140000,
      rating: 4.8,
      joinedDate: "05 Nov 2024",
      bankDetails: { bank: "Federal Bank", acc: "•••• •••• 6023", ifsc: "FDRL0001390", upi: "mfarooq@federal" },
      recentPayouts: [
        { id: "PAY-16", date: "04 Apr 2026", amount: "₹2.80 L", property: "Riverside Waterfront Penthouse", status: "Paid" }
      ]
    },
    {
      id: "AG-106",
      name: "Kavitha Krishnan",
      agency: "Coromandel Property Advisory",
      type: "Agency Partner",
      tier: "Silver",
      reraNo: "TN/AGENT/0441/2023",
      outlets: ["YOR South", "YOR Central"],
      outlet: "Multi-Hub (South, Central)",
      city: "Chennai",
      state: "Tamil Nadu",
      phone: "+91 98404 67890",
      email: "kavitha@coromandeladvisory.com",
      photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Coastal Beach Villas & OMR Tech Corridor",
      commissionRate: "2.0%",
      propertiesConnected: [
        { id: "PROP-004", name: "Marina Sea Breeze Residences", surveyNo: "90/4", valuation: "₹18.6 Cr", location: "OMR, Chennai", outlet: "YOR South", state: "Tamil Nadu", type: "Residential" }
      ],
      activeLeads: 7,
      dealsClosed: 9,
      totalSalesVolume: "₹13.5 Cr",
      rawSalesVolume: 135000000,
      totalCommissionEarned: "₹6.75 L",
      rawCommissionEarned: 675000,
      commissionPaid: "₹5.20 L",
      rawCommissionPaid: 520000,
      commissionPending: "₹1.55 L",
      rawCommissionPending: 155000,
      rating: 4.6,
      joinedDate: "12 Dec 2024",
      bankDetails: { bank: "State Bank of India", acc: "•••• •••• 3411", ifsc: "SBIN0004128", upi: "kavitha.k@sbi" },
      recentPayouts: [
        { id: "PAY-24", date: "14 Apr 2026", amount: "₹1.80 L", property: "Marina Sea Breeze Residences", status: "Paid" }
      ]
    },
    {
      id: "AG-107",
      name: "Deepak Verma",
      agency: "Urban Crest Real Estate",
      type: "Independent Broker",
      tier: "Silver",
      reraNo: "K-RERA/AG/0189/2023",
      outlets: ["YOR North", "YOR Central", "YOR West"],
      outlet: "Multi-Hub (North, Central, West)",
      city: "Kannur",
      state: "Kerala",
      phone: "+91 98415 78901",
      email: "deepak.verma@urbancrest.in",
      photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Residential Plots & Layouts",
      commissionRate: "2.0%",
      propertiesConnected: [
        { id: "PROP-006", name: "Capital Boulevard Prime Estate", surveyNo: "67/9", valuation: "₹14.2 Cr", location: "Golf Course Road, Gurugram", outlet: "YOR North", state: "Delhi NCR", type: "Commercial" }
      ],
      activeLeads: 5,
      dealsClosed: 6,
      totalSalesVolume: "₹8.2 Cr",
      rawSalesVolume: 82000000,
      totalCommissionEarned: "₹4.10 L",
      rawCommissionEarned: 410000,
      commissionPaid: "₹3.40 L",
      rawCommissionPaid: 340000,
      commissionPending: "₹0.70 L",
      rawCommissionPending: 70000,
      rating: 4.5,
      joinedDate: "08 Jan 2025",
      bankDetails: { bank: "Canara Bank", acc: "•••• •••• 9012", ifsc: "CNRB0002100", upi: "deepakv@okcanara" },
      recentPayouts: [
        { id: "PAY-28", date: "09 Mar 2026", amount: "₹1.20 L", property: "Capital Boulevard Prime Estate", status: "Paid" }
      ]
    },
    {
      id: "AG-108",
      name: "Michael Wong",
      agency: "Capital Horizon Advisory",
      type: "Channel Partner",
      tier: "Gold",
      reraNo: "K-RERA/AG/0088/2021",
      outlets: ["All Outlets", "YOR Central", "YOR South", "YOR North", "YOR East", "YOR West"],
      outlet: "Pan-India (All Outlets)",
      city: "Kochi",
      state: "Kerala",
      phone: "+91 98426 89012",
      email: "michael.wong@capitalhorizon.com",
      photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "High-Yield Commercial & Rental Portfolios",
      commissionRate: "2.5%",
      propertiesConnected: [
        { id: "PROP-002", name: "Riverside Waterfront Penthouse", surveyNo: "144/3B", valuation: "₹8.4 Cr", location: "Marine Drive, Kochi", outlet: "YOR Central", state: "Kerala", type: "Residential" },
        { id: "PROP-003", name: "Cyber Pearl Commercial Tech Park", surveyNo: "456/38", valuation: "₹25.0 Cr", location: "HITEC City, Hyderabad", outlet: "YOR Central", state: "Telangana", type: "Commercial" }
      ],
      activeLeads: 6,
      dealsClosed: 11,
      totalSalesVolume: "₹17.0 Cr",
      rawSalesVolume: 170000000,
      totalCommissionEarned: "₹8.50 L",
      rawCommissionEarned: 850000,
      commissionPaid: "₹7.20 L",
      rawCommissionPaid: 720000,
      commissionPending: "₹1.30 L",
      rawCommissionPending: 130000,
      rating: 4.7,
      joinedDate: "18 Feb 2024",
      bankDetails: { bank: "Standard Chartered", acc: "•••• •••• 5529", ifsc: "SCBL0036001", upi: "mwong@scb" },
      recentPayouts: [
        { id: "PAY-03", date: "08 Apr", amount: "₹1.27 L", property: "Maple Residences", status: "Pending" }
      ]
    },
    {
      id: "AG-109",
      name: "Ayesha Siddiqui",
      agency: "Royal Palm Agency",
      type: "Independent Broker",
      tier: "Silver",
      reraNo: "K-RERA/AG/0224/2024",
      outlets: ["YOR East", "YOR South", "YOR Central"],
      outlet: "Multi-Hub (East, South, Central)",
      city: "Kottayam",
      state: "Kerala",
      phone: "+91 98437 90123",
      email: "ayesha@royalpalmagency.com",
      photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Plantation Estates & Luxury Farmhouses",
      commissionRate: "2.0%",
      propertiesConnected: [
        { id: "PROP-001", name: "Green Valley Plot", surveyNo: "123/2A", valuation: "₹12.5 Cr", location: "Devenahalli, Bengaluru", outlet: "YOR South", state: "Karnataka", type: "Land" }
      ],
      activeLeads: 4,
      dealsClosed: 5,
      totalSalesVolume: "₹6.3 Cr",
      rawSalesVolume: 63000000,
      totalCommissionEarned: "₹3.15 L",
      rawCommissionEarned: 315000,
      commissionPaid: "₹2.60 L",
      rawCommissionPaid: 260000,
      commissionPending: "₹0.55 L",
      rawCommissionPending: 55000,
      rating: 4.6,
      joinedDate: "10 Feb 2025",
      bankDetails: { bank: "South Indian Bank", acc: "•••• •••• 1204", ifsc: "SIBL0000188", upi: "ayeshas@oksbi" },
      recentPayouts: [
        { id: "PAY-30", date: "12 Mar 2026", amount: "₹0.95 L", property: "Green Valley Plot", status: "Paid" }
      ]
    },
    {
      id: "AG-110",
      name: "Rahul Kapoor",
      agency: "Matrix Commercial Partners",
      type: "Channel Partner",
      tier: "Platinum",
      reraNo: "K-RERA/AG/0099/2022",
      outlets: ["All Outlets", "YOR West", "YOR North", "YOR South", "YOR Central"],
      outlet: "Pan-India (All Outlets)",
      city: "Idukki",
      state: "Kerala",
      phone: "+91 98448 01234",
      email: "rahul.kapoor@matrixcommercial.in",
      photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
      status: "Active",
      specialization: "Eco-Resorts & Commercial Land Development",
      commissionRate: "3.0%",
      propertiesConnected: [
        { id: "PROP-005", name: "The Lennox Luxury Penthouse", surveyNo: "221/11A", valuation: "₹32.0 Cr", location: "Worli, Mumbai", outlet: "YOR West", state: "Maharashtra", type: "Residential" },
        { id: "PROP-006", name: "Capital Boulevard Prime Estate", surveyNo: "67/9", valuation: "₹14.2 Cr", location: "Golf Course Road, Gurugram", outlet: "YOR North", state: "Delhi NCR", type: "Commercial" }
      ],
      activeLeads: 7,
      dealsClosed: 10,
      totalSalesVolume: "₹21.6 Cr",
      rawSalesVolume: 216000000,
      totalCommissionEarned: "₹10.80 L",
      rawCommissionEarned: 1080000,
      commissionPaid: "₹8.90 L",
      rawCommissionPaid: 890000,
      commissionPending: "₹1.90 L",
      rawCommissionPending: 190000,
      rating: 4.9,
      joinedDate: "01 Mar 2024",
      recentPayouts: [
        { id: "PAY-32", date: "20 Apr 2026", amount: "₹2.90 L", property: "The Lennox Luxury Penthouse", status: "Paid" }
      ]
    }
  ],

  // Outlets Register
  outlets: [
    { id: "OUT-1", name: "YOR Central", location: "Kochi, Kerala", admin: "Adrian Tan", users: 28, properties: 256, status: "Active" },
    { id: "OUT-2", name: "YOR North", location: "Kannur, Kerala", admin: "Siti Rahman", users: 18, properties: 182, status: "Active" },
    { id: "OUT-3", name: "YOR South", location: "Kozhikode, Kerala", admin: "Rahul Nair", users: 16, properties: 224, status: "Active" },
    { id: "OUT-4", name: "YOR East", location: "Kottayam, Kerala", admin: "May Lim", users: 12, properties: 145, status: "Active" },
    { id: "OUT-5", name: "YOR West", location: "Idukki, Kerala", admin: "Daniel Lee", users: 14, properties: 108, status: "Active" }
  ],

  // User Directory & Role Hierarchy
  users: [
    { id: "U-1", name: "Siyad Sirajudeen", email: "admin@yorestate.com", role: "Main / Super Admin", scope: "Global platform oversight", lastLogin: "Just now", status: "Active" },
    { id: "U-2", name: "Asha Menon", email: "asha@yorestate.com", role: "Head Office Admin", scope: "Central operations", lastLogin: "10 min ago", status: "Active" },
    { id: "U-3", name: "Rahul Nair", email: "rahul@yorestate.com", role: "Outlet Admin", scope: "YOR South", lastLogin: "1 hr ago", status: "Active" },
    { id: "U-4", name: "Priya Das", email: "priya@yorestate.com", role: "Finance Team", scope: "Cross-outlet finance", lastLogin: "Yesterday", status: "Active" },
    { id: "U-5", name: "Arjun Mehta", email: "arjun@yorestate.com", role: "Sales Team", scope: "YOR Central", lastLogin: "2 days ago", status: "Active" },
    { id: "U-6", name: "Tan Wei Ming", email: "investor@yorestate.com", role: "Investor (External)", scope: "Own investment records", lastLogin: "3 days ago", status: "Active" },
    { id: "U-7", name: "Sarah Lim", email: "sarah.agent@yorestate.com", role: "Agent / Broker (External)", scope: "Assigned properties & leads", lastLogin: "Yesterday", status: "Active" }
  ],

  // Platform & Web Global Configuration Settings
  generalSettings: {
    // Basic Web & Platform Identity
    platformName: "YOR Estate & Property Management",
    companyLegalName: "YOR Estate and Property Management Pvt. Ltd.",
    tagline: "Property. Compliance. Performance.",
    cinNumber: "U70109KA2024PTC189421",
    gstin: "29AABCY9841K1Z5",
    supportEmail: "support@yorestate.com",
    supportPhone: "+91 80 4920 1800",
    headOfficeAddress: "Tower B, Level 14, Prestige Trade Tower, Palace Road, High Grounds, Bengaluru, Karnataka 560001",
    
    // Regional & Localization
    defaultCurrency: "INR",
    currencySymbol: "₹",
    numberFormat: "indian", // indian (Lakhs/Crores) | international (Millions/Billions)
    financialYearStart: "april", // april | january
    defaultState: "Karnataka",
    timezone: "Asia/Kolkata (IST +5:30)",
    dateFormat: "DD/MM/YYYY",
    defaultLanguage: "English (UK / India)",
    
    // Branding & Theme Styling
    themeAccent: "gold", // gold, obsidian, emerald, cobalt
    enableGlassmorphism: true,
    showLiveValuationTicker: true,
    defaultLandingRoute: "dashboard",
    
    // Security & Role Policies
    sessionTimeoutMinutes: 60,
    enforce2FAForAdmins: true,
    minPasswordLength: 8,
    requireSpecialCharInPassword: true,
    passwordExpiryDays: 90,
    ipWhitelistEnabled: false,
    ipWhitelist: "103.120.44.0/24, 49.207.180.12",
    auditLogRetentionDays: 365,
    
    // Notifications & Automated Triggers
    enableEmailAlerts: true,
    enableSmsWhatsAppAlerts: true,
    smsGateway: "Twilio Enterprise",
    alertOnLegalIntake: true,
    alertOnHoSignoff: true,
    ecExpiryAlertDays: 30,
    webhookEndpoint: "https://api.yorestate.com/v1/webhooks/compliance"
  }
};

